antfu/eslint-config

- packages/basic/index.js
Hi, I am studying eslint rules recently and found that the `no-spaced-func` in the project has been deprecated in `eslint v3.3.0`, but the `eslint` version in `peerDependencies` is `>=7.4.0`, so I think this rule can be deleted.
[more to see](https://eslint.org/docs/rules/no-spaced-func#disallow-spacing-between-function-identifiers-and-their-applications-no-spaced-func)
> fix: `no-spaced-func` was deprecated in v3.3.0

- packages/basic/index.js
I see that. Maybe we just need `plugin:import/recommended`.
```yaml
extends:
- eslint:recommended
- plugin:import/recommended
- plugin:import/errors
- plugin:import/warnings
```
> https://github.com/benmosher/eslint-plugin-import#installation
> refactor: simplify eslint-plugin-import extend

- packages/basic/index.js
According to the [`eqeqeq` rule docs](https://eslint.org/docs/rules/eqeqeq#allow-null) - option `allow-null` is deprecated.
https://eslint.org/docs/rules/eqeqeq#allow-null
> Deprecated: Instead of using this option use "always" and pass a "null" option property with value "ignore". This will tell ESLint to always enforce strict equality except when comparing with the null literal.
This PR fixes it to use the null option.
**NOTICE**: If you prefer, `eqeqeq` has also [`smart` option](https://eslint.org/docs/rules/eqeqeq#smart) instead of `always` but it behaves differently.
> fix: `eqeqeq` rule deprecated option allow-null

- packages/basic/index.js
- packages/typescript/index.js
`eslint-plugin-import` does not support TypeScript by default , and `plugin:import/typescript` configuration needs to be added.
reference：
- [eslint-plugin-import support TypeScript](https://github.com/import-js/eslint-plugin-import#typescript)
- [useful stuff for folks using various environments](https://github.com/import-js/eslint-plugin-import/blob/main/src/index.js#L68)
> fix: eslint-plugin-import support TypeScript

- packages/basic/index.js
- packages/basic/standard.js
related issue: [83](https://github.com/antfu/eslint-config/issues/83)
solution: [eslint docs](https://eslint.org/docs/rules/space-before-function-paren#anonymous-always-named-never-asyncarrow-always)
> fix: space-before-function-paren allows space in anonymous and asyncArrow function.

- packages/basic/standard.js
- packages/typescript/index.js
I noticed the typescript overrides are not complete, eg. `space-infix-ops` is not present so it doesn't work on unions.
So I spent some time iterated through the docs and added overrides for all that `typescript-eslint` recommended to.
I haven't tested it, but it should work.
> fix: complete typescript overrides

- packages/typescript/index.js
[no-parameter-properties](https://github.com/typescript-eslint/typescript-eslint/blob/88ed9ec9d6b971a9533565920fdcd6890ea941e9/packages/eslint-plugin/src/rules/no-parameter-properties.ts#L23)
[camelcase](https://typescript-eslint.io/rules/camelcase)
> fix: remove deprecated rules

- packages/basic/index.js
https://ota-meshi.github.io/eslint-plugin-jsonc/rules/#extension-rules
> fix: add missing extension rules

- packages/basic/index.js
`no-array-instanceof` was renamed to `no-instanceof-array` [deprecated-rules](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/deprecated-rules.md#no-array-instanceof)
> fix: rule renamed

- packages/basic/index.js
`unicorn/prefer-exponentiation-operator` was deprecated since 16.0.0 [deprecated-rules](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/deprecated-rules.md#prefer-exponentiation-operator)
> fix: deprecated rule

- packages/basic/index.js
`jiti` (`mlly`) will load exports by the order in `package.json`. Since `jiti` needs to transpile ESM files, it's generally better to make CJS export prioritized.
> fix: prioritize require

- packages/basic/index.js
- packages/basic/package.json
- pnpm-lock.yaml
Introduce [eslint-plugin-no-only-tests](https://github.com/levibuzolic/eslint-plugin-no-only-tests) to prevent `.only` in tests
Fixed #121
> feat(basic): add rules to prevent `.only` in tests

- packages/basic/index.js
It's used by 'electron-vite' as output directory for example.
> Added 'out' to ignorePatterns

- packages/basic/index.js
```js
require('eslint')
// empty line
// empty line
```
Files that have multi empty lines at the end should throw error when linting.
But it doesn't work actually.
This PR Fix this problem.
See https://github.com/eslint/eslint/issues/12742#issuecomment-570904439
> fix(basic): disallow multi empty lines at the end of file

- packages/typescript/index.js
- packages/typescript/package.json
- pnpm-lock.yaml
Hi. Enabling `@typescript-eslint/unbound-method` will make some trouble when using `jest` or `vitest`. This PR will convenient for writing unit test.
See https://github.com/jest-community/eslint-plugin-jest/blob/main/docs/rules/unbound-method.md
> feat(ts): enable `jest/unbound-method`

- README.md
- packages/basic/index.js
- packages/typescript/index.js
```ts
// main.ts
/* eslint-disable @typescript-eslint/require-await */
async function test() {
return 'test'
}
setTimeout(() => {
void test()
})
export {}
```
Let's say I have code above. Run lint will cause `no-void` error. But after adding `tsconfig.eslint.json` file to project root, this error will disappear. 
I think, adding `tsconfig.eslint.json` file to the root of project should bring more stricter rules to project. Deleting the `tsconfig.eslint.json` file should remove some stricter rules. But in the example above, deleting the `tsconfig.eslint.json` file will bring more stricter rule, which should not be.
> fix: allow void as statement in ts file

- packages/basic/standard.js
Using both `&&`, `||` and `?:` makes it hard to figure out their precedence without group
Ref https://github.com/antfu/sponsorkit/pull/36
> fix: group `&&`, `||` and `?:`

- packages/eslint-config-ts/index.js
We should stick to `esm`. `import = require()` is the grammar belongs to ts only. Just forget them. Use `import` only.
See the [doc](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-require-imports.md).
> feat: ban requrie imports in ts file

- packages/eslint-plugin-antfu/src/rules/top-level-function.test.ts
- packages/eslint-plugin-antfu/src/rules/top-level-function.ts
> feat(plugin): allow some one-line arrow functions

- packages/eslint-config-ts/index.js
- packages/eslint-plugin-antfu/src/index.ts
- packages/eslint-plugin-antfu/src/rules/no-cjs-exports.test.ts
- packages/eslint-plugin-antfu/src/rules/no-cjs-exports.ts
- packages/eslint-plugin-antfu/src/rules/no-ts-export-equal.test.ts
- packages/eslint-plugin-antfu/src/rules/no-ts-export-equal.ts
Ban cjs exports in ts file.
```ts
if (true)
module.exports = {}
module.exports = {}
if (true)
exports.a = 1
exports.a = 1
function f() {
exports.a = 1
}
const a = {
exports: {
tmp: 'hi',
},
}
a.exports.tmp = 'hello'
export = 'abc'
export default 'hello'
export const tmp = 'world'
```
Copy this content to test.
> feat(ts): ban cjs exports in ts file

- packages/eslint-config-basic/index.js
Although we can use `global` object in Node environment, it is not a standard object. `globalThis` is the standard which can be used in browser and Deno.
> feat(basic): ban `global` variable

- README.md
With the default configuration for VSCode, there is a race condition when saving a file with ordering imports. 
This happens because there is an `import/order` rule configured.
With the following settings it respects the linter and will work as expected:
```diff
"editor.codeActionsOnSave": {
"source.fixAll.eslint": true,
+   "source.organizeImports": false
}
```
> docs: update `organizeImports` config for VS Code

- packages/eslint-config-ts/index.js
- packages/eslint-plugin-antfu/src/index.ts
- packages/eslint-plugin-antfu/src/rules/no-const-enum.test.ts
- packages/eslint-plugin-antfu/src/rules/no-const-enum.ts
There are so many issues about `const enum`. Just forget this feature and use `enum` only.
Please check:
- https://www.typescriptlang.org/docs/handbook/enums.html#const-enum-pitfalls
- https://github.com/microsoft/rnx-kit/tree/main/packages/eslint-plugin
> feat(ts): ban `const enum`

- README.md
This PR adds the recommended configuration for the ESLint VSCode extension to enable it to lint all supported filetypes from this eslint-config.
Fix #153
> docs: add `eslint.validate` to enable linting for supported filetypes with VSCode ESLint

- packages/eslint-config-ts/index.js
https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/ban-types.md
According to the doc, I think this rule is reasonable to enable.
Is there any chance to enable this? Or may I get the reason to disable this?
> feat(ts): enable `@typescript-eslint/ban-types`

- packages/eslint-config-basic/index.js
The parameter of Array constructor is the design mistake which is ambiguous and hard to use. Banning this will be convenient for code review. Because some time I will forget:
```js
new Array(5) // An array with 5 items? Or one item in an array?
```
> feat: ban `new Array`

- README.md
Fixes a mistake in a code example in the README.md file.  The `eslint.validate` option was mistakenly inside the `editor.codeActionsOnSave` option.
> docs: VS Code config example

- packages/eslint-config-basic/index.js
I've re-thought it carefully.
- For people who use vite, they should use `import.meta.env.PROD`. See  https://vitejs.dev/guide/env-and-mode.html.
- For people who use webpack, they should use `new webpack.DefinePlugin({'import.meta.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV)})` to inject it. See https://webpack.js.org/plugins/environment-plugin/
Any way, we should not use `process.env` in frontend projects. So enable this rule will benefit node projects.
BTW, why did not  vite document mention the `process.env` but `import.meta.env`? Maybe vite author do not recommend us to use `process.env` in frontend project. 😆
https://github.com/antfu/eslint-config/pull/159
> feat(basic): prefer non global process object

- packages/eslint-plugin-antfu/src/rules/prefer-inline-type-import.test.ts
- packages/eslint-plugin-antfu/src/rules/prefer-inline-type-import.ts
Allow the case below, instead of removing `type` keyword
```ts
import type {} from 'vite'
```
> fix(plugin): allow empty type import

- packages/eslint-config-ts/index.js
- packages/eslint-plugin-antfu/src/index.ts
- packages/eslint-plugin-antfu/src/rules/named-tuple-spacing.test.ts
- packages/eslint-plugin-antfu/src/rules/named-tuple-spacing.ts
Vue 3.3 provides [a new way to define props](https://vuejs.org/guide/typescript/composition-api.html#typing-component-emits), which leverages [named tuples](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-0.html#labeled-tuple-elements): 
```ts
const emit = defineEmits<{
change: [id: number]
update: [value: string]
}>()
```
However, I didn't find a ESLint rule that checks spaces between colon in named tuples. It would be nice to have one. 
```ts
// good
type T = [i: number]
const emit = defineEmits<{
change: [id: number]
update: [value: string]
}>()
```
```ts
// bad
type T = [i:number]
type T = [i : number]
const emit = defineEmits<{
change: [id:number]
update: [value:string]
}>()
```
> feat: format for named tuple

- packages/eslint-config-basic/index.js
- packages/eslint-plugin-antfu/src/index.ts
- packages/eslint-plugin-antfu/src/rules/no-import-node-modules-by-path.test.ts
- packages/eslint-plugin-antfu/src/rules/no-import-node-modules-by-path.ts
Prevent some codes like `import xx from './node_modules/xxx'`
> feat: add rule `no-import-node-modules-by-path`

- packages/eslint-config-basic/index.js
`.vitepress/cache` is can not ignore `docs/.vitepress/cache/**` in monorepo app.
ignorePatterns change:
`.vitepress/cache` -> `**/.vitepress/cache`
> fix(basic): ignore vitepress cache files

- packages/eslint-config-vue/index.js
Two rules of `vue` are deprecated and replaced by others.
1. [`vue/component-tags-order`](https://eslint.vuejs.org/rules/component-tags-order.html) was deprecated and replaced by [`vue/block-order`](https://eslint.vuejs.org/rules/block-order) rule.
2. [`vue/no-setup-props-destructure`](https://eslint.vuejs.org/rules/no-setup-props-destructure.html) was deprecated and replaced by [`vue/no-setup-props-reactivity-loss`](https://eslint.vuejs.org/rules/no-setup-props-reactivity-loss.html) rule.
> feat(vue): replace deprecate rules of vue

- packages/eslint-config-basic/index.js
Ts project, which enabled [noPropertyAccessFromIndexSignature](https://www.typescriptlang.org/tsconfig#noPropertyAccessFromIndexSignature), will have conflict with `dot-notation`. 
[Line 36](https://github.com/antfu/eslint-config/blob/main/packages/typescript/index.js#L36) has enabled `@typescript-eslint/dot-notation`. So, we can disable `dot-notation` in ts file. People who want to enable `dot-notation` can enable type aware rules by adding `tsconfig.eslint.json` file.
> feat: improve compatibility with `noPropertyAccessFromIndexSignature`

- packages/eslint-config-basic/index.js
When I use import { createApp } from 'vue' in JavaScript file,eslint error `createApp not found in 'vue'`,not install TypeScript
> fix(basic): JavaScript vue import error

- packages/eslint-config-basic/index.js
- packages/eslint-config-ts/index.js
fix: Definition for rule '@stylistic/ts/comma-dangle' was not found
> fix: revert '@stylistic/ts/comma-dangle' rule

- src/configs/yaml.ts
Using tabs in yaml is a syntax error nor a valid argument value of `yaml/indent`, so we should enforce 2 spaces when user uses tabs.
> fix: yaml indent

- src/configs/unicorn.ts
The `no-unsafe-regex` rule from eslint-plugin-unicorn has already been deprecated in https://github.com/sindresorhus/eslint-plugin-unicorn/pull/2135
> chore(unicorn): remove deprecated rule `no-unsafe-regex`

- src/configs/vue.ts
fix #288
added optional param for `vue/component-name-in-template-casing`
vue/component-name-in-template-casing doesn't work when the component is global or auto-imported (like in nuxt).
#288
> fix: enforce name casing for unregistered components

- .npmrc
This PR is in draft while I check that the problem mentioned in https://github.com/antfu/eslint-config/issues/284#issuecomment-1761587177 is not a result of this change.
`nr dev` runs tsup in watch mode and eslint-flat-config-viewer. Both commands run indefinitely and therefore need to be executed concurrently. I assume that this is achieved by the & sign on Unix-based systems, however on my Windows systems only the first command is executed.
This is fixed by enabling shell-emulator as suggested in https://github.com/antfu/eslint-config/issues/284 by @antfu.
Closes #284
> chore: run `nr dev` scripts concurrently on windows

- src/configs/vue.ts
This reverts commit ba704e78711236c34318470ff211956a13012ae0.
Reverting change as it breaks camel case components which are imported within SFC itself, even though it is valid SFC syntax. For example, using `framework7-vue` where component names are prefixed with `f7`:
```vue
<script setup lang="ts">
import { f7Button } from 'framework7-vue'
</script>
<template>
<f7Button>Hello</f7Button>
</template>
```
It will get fixed to 
```vue
<script setup lang="ts">
</script>
<template>
<F7Button>Hello</F7Button>
</template>
```
Which is invalid.
NA
Related [comment](https://github.com/antfu/eslint-config/pull/289#issuecomment-1783870934).
> fix: revert #289

- README.md
- src/configs/typescript.ts
- src/types.ts
- src/utils.ts
Multiple tsconfigs support
```ts
typescript: {
tsconfigPath: ['tsconfig.json', 'tsconfig.node.json']
}
```
close #305
> feat: typescript.tsconfigPath array support

- src/utils.ts
https://github.com/antfu/eslint-config/blob/51639fde52747c60f5aae90dc3b6330997385145/src/utils.ts#L6-L8
The flatMap() operation seems to have the same effect as flat().
```ts
export function combine(...configs: (ConfigItem | ConfigItem[])[]): ConfigItem[] {
return configs.flat()
}
```
> chore: optimize combine function using flat()

- README.md
using `export default await antfu()` causes eslint-flat-config-viewer to error with the message "await is not defined".
> docs: remove await from config examples

- src/configs/react.ts
fix https://github.com/antfu/eslint-config/issues/341
When running the optional react config, it prints the following warning
`Warning: React version not specified in eslint-plugin-react settings. See https://github.com/jsx-eslint/eslint-plugin-react#configuration`
this pr, fix the message above :)
> fix: warning when running react

- src/configs/vue.ts
use wrong key for vue2 presets. 
https://eslint.vuejs.org/rules/#priority-a-essential-error-prevention
> fix: vue2 presets name

- src/factory.ts
Make `isInEditor` detect vim/nvim. Uses [`$VIM`](https://neovim.io/doc/user/starting.html#_-$vim-and-$vimruntime) env var for detection.
> feat: detect if in (n)vim editor

- README.md
To enable the git hooks which are described in [Lint Staged](https://github.com/antfu/eslint-config?tab=readme-ov-file#lint-staged) you have to run `npx simple-git-hooks`.
This is not part of a automatic postinstall script.
Simple Git Hooks Documentation: [Add simple-git-hooks to the project](https://github.com/toplenboren/simple-git-hooks?tab=readme-ov-file#add-simple-git-hooks-to-the-project)
With this pull request I added the necessary command to the code block
> docs: enhanced "Lint Staged" part

- fixtures/input/svelte.svelte
- fixtures/output/all/svelte.svelte
- package.json
- pnpm-lock.yaml
- src/configs/svelte.ts
- test/fixtures.test.ts
eslint ignore directives are not being honored when placed in a `.svelte` file. This PR adds the processor from `eslint-plugin-svelte` to the svelte eslint configuration so that these rules can be detected.
Before this PR, this eslint directive would have no effect:
```svelte
<article>
<div>{@html content}</div>
</article>
```
N/A
I've added a fixture to `all` that includes svelte. Please check that I've added the test correctly.
> fix: honor eslint-disable-next-line in svelte files

- src/configs/javascript.ts
Error: Invalid Options:
- Unknown options: reportUnusedDisableDirectives
- 'reportUnusedDisableDirectives' has been removed. Please use the 'overrideConfig.linterOptions.reportUnusedDisableDirectives' option instead.
> fix: Unknown options: reportUnusedDisableDirectives

- src/types.ts
Fixed #391.
#391 
If I didn't miss something, I think it's only a type change.
I aware that `OptionsVue`, `OptionsTypescript`, 'OptionsUnoCSS' etc extends `OptionsOverrides` directly, but `OptionsStylistic` and `StylisticConfig` seems has different usages.
> fix: add override options type for stylistic (closes #391)

- src/configs/svelte.ts
Turn off `style/indent` in favor `svelte/indent` as per [docs](https://sveltejs.github.io/eslint-plugin-svelte/rules/indent/). This is only applicable to `*.svelte` files.
Fix #399 
Not sure how this flew under the radar this long
> fix(svelte): disable style/indent in svelte files

- src/factory.ts
fix: https://github.com/antfu/eslint-config/issues/401
> fix: use `VSCODE_CWD` to autodetect if in editor

- src/globs.ts
Ignore the `.yarn` folder by default. The folder is created by yarn berry and contains its minified source code with an unlimited `/* eslint-disable */` comment, which upsets the `eslint-comments/no-unlimited-disable` rule.
N/A
N/A
> fix: ignore `.yarn` folder

- README.md
- src/configs/formatters.ts
- src/globs.ts
Adding glob for GraphQL files. Currently only .graphql files are recognized. Another common and shorter filename is .gql.
Also added info about configuring eslint for VSCode to support gql files.
> feat: graphql glob that supports .qgl extensions

- package.json
- pnpm-lock.yaml
`@antfu/install-pkg` v0.3.2 enables installing dependencies on pnpm workspace, which can be very helpful if developers use `@antfu/eslint-config` and execute eslint on a pnpm workspace root directory. It solves conditions like below
FYI: https://github.com/antfu/install-pkg/pull/10
None
> chore: bump `@antfu/install-pkg` to ^0.3.2

- src/configs/svelte.ts
This PR attempts to add `$$Events` and `$$Slots` as known variables, similar to `$$Props` for the `svelte` plugin.
It follows from the [official RFC for typing Svelte components](https://github.com/sveltejs/rfcs/pull/38).
N/A
No tests failed on the local production build but AFAIK there don't seem to be any specific tests for Svelte files that have components with typing information.
> feat(svelte): add support for typing according to sveltejs/rfcs#38

- README.md
- package.json
- pnpm-lock.yaml
- src/cli/constants.ts
- src/configs/react.ts
- src/factory.ts
- src/stub.d.ts
- src/types.ts
close #452 
Sorry for direct ping, maybe @rel1cx @sukkaw would like to look at this.
> refactor!: migrate from eslint-plugin-react to eslint react

- src/configs/react.ts
> fix(react): improve option for react-refresh, aware Remix and Next.js

- src/configs/typescript.ts
This commit adds the 'ts/strict-boolean-expressions' rule to the TypeScript ESLint configuration. This rule helps to prevent bugs caused by the incorrect use of boolean expressions.
add `strict-boolean-expressions` to type-aware rule
https://typescript-eslint.io/rules/strict-boolean-expressions/#:~:text=Disallow%20certain%20types%20in%20boolean%20expressions.&text=Some%20problems%20reported%20by%20this,fix%20ESLint%20command%20line%20option.
> feat(typescript): add strict-boolean-expressions rule

- src/factory.ts
This PR provides a fix to access to the `tsconfigPath` option in the factory function using resolveSubOptions instead of getOverrides.
fix https://github.com/antfu/eslint-config/issues/489
> fix: tsconfigPath undefined

- package.json
I think this fixes #503. I can't verify the fix locally because I don't know how to reproduce the original error locally when using `npm link`. Also tried [`pnpm link`](https://pnpm.io/cli/link) with [`strict-peer-dependencies=true`](https://pnpm.io/npmrc#strict-peer-dependencies), but `pnpm install eslint-plugin-svelte` always exits successfully.
Anyways this PR:
1. Loosens the peer dep range. It was `~X.X.X` and now it's `>=X.X.X`
1. I also updated the peer dep version to the latest one. I figured since we're using the latest version so should our consumers.
Either way, since the change is very minimal I figured I'd just send the PR and someone with more knowledge than me can maybe eyeball it. Feel free to close this PR if it doesn't look right.
#503
> fix: peer dependency version of svelte-eslint-parser

- src/factory.ts
add nvim support for isInEditor
> feat: add nvim support for `isInEditor`

- src/configs/typescript.ts
This commit adds the 'ts/return-await' rule to the TypeScript configuration. This rule enforces that 'return await' is used in async functions.
https://typescript-eslint.io/rules/return-await
> feat(typescript): add 'ts/return-await' rule

- src/configs/typescript.ts
This commit adds the 'ts/switch-exhaustiveness-check' rule to the TypeScript configuration. This rule helps ensure that all possible cases in a switch statement are handled.
https://typescript-eslint.io/rules/switch-exhaustiveness-check
Without this PR, it causes an error like below:
```
Error: Error while loading rule 'ts/switch-exhaustiveness-check': You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser.
Parser: undefined
Note: detected a parser other than @typescript-eslint/parser. Make sure the parser is configured to forward "parserOptions.project" to @typescript-eslint/parser.```
> feat(typescript): add `ts/switch-exhaustiveness-check` rule

- src/globs.ts
`vite.config.*.timestamp-*` file should be ignore
> fix: ignore vite timestamp file

- src/configs/typescript.ts
This commit introduces a new rule 'ts/promise-function-async' to the TypeScript configuration. This rule enforces the use of async keyword when a function returns a Promise.
https://typescript-eslint.io/rules/promise-function-async
> feat(typescript): add 'ts/promise-function-async' to type aware rule

- src/configs/react.ts
This PR replaces the react config default files individual glob patterns (`[GLOB_JS, GLOB_JSX, GLOB_TS, GLOB_TSX]`) with a single unified pattern (`[GLOB_SRC]`). The new pattern `'**/*.?([cm])[jt]s?(x)'` covers all the specific cases previously handled by the separate patterns, reducing redundancy and simplifying the configuration.
> chore: replace react default files glob patterns `[GLOB_JS, GLOB_JSX, GLOB_TS, GLOB_TSX]` to `[GLOB_SRC]`

- src/globs.ts
With the out-of-the box config and svelte plugin enabled, files in the auto-generated `.svelte-kit` directory are linted.
This simple PR adds `'**/.svelte-kit'` to `GLOB_EXCLUDE`.
> fix: Add `.svelte-kit` to ignored paths

- src/types.ts
Follow up PR from https://github.com/antfu/eslint-config/pull/541, since`projectService.defaultProject` not support array the type should not allow user to be able to pass an array of string.
> fix(typescript): remove string[] from tsconfigPath as not supported in v8

- src/factory.ts
In a monorepo, you may only have a single `.gitignore` at the root of the repo, but run the eslint from within package subdirectories. In this scenario, `@antfu/eslint-config` doesn't currently add gitignore entries to the eslint ignores.
This PR enables `eslint-config-flat-gitignore` even if a `.gitignore` is not present in the current directory, as it has `find-up-simple` to look for a `.gitignore` in a higher directory.
I've set `{ strict: false }` so that it doesn't error if it can't find a `.gitignore` file at all.
Fixes #544
> fix: enable `eslint-config-flat-gitignore` even if `.gitignore` is not in cwd

- src/configs/typescript.ts
When I was reviewing the [typescript-eslint](https://typescript-eslint.io/rules/prefer-ts-expect-error/) documentation, I came across the following statement :
“This rule has been deprecated in favor of [@typescript-eslint/ban-ts-comment](https://typescript-eslint.io/rules/ban-ts-comment). This rule (@typescript-eslint/prefer-ts-expect-error) will be removed in a future major version of typescript-eslint.”
> fix: remove deprecated 'ts/prefer-ts-expect-error' rule

- src/configs/formatters.ts
Default prettier `printWidth: 120` not work for `css` as pointed here:
https://github.com/antfu/eslint-config/blob/1215d9fd98e4b6fee57453312a22c2340c91f085/src/vender/prettier-types.ts#L7-L12
`printWidth: 120` is only set for `markdown` / `slidev`, others will fallback to use prettier's default `80`.
In the following reproduction project: 
[stackblitz.com/~/github.com/HADB/eslint-config-prettier-printWidth-bug-reproduction?file=assets/styles.css](https://stackblitz.com/~/github.com/HADB/eslint-config-prettier-printWidth-bug-reproduction?file=assets/styles.css)
```css
body {
font-family: 'LXGW WenKai GB', 'LXGW WenKai', '仿宋', 'FangSong', 'STFangsong', 'serif';
}
```
will be formatted to:
```css
body {
font-family: 'LXGW WenKai GB', 'LXGW WenKai', '仿宋', 'FangSong', 'STFangsong',
'serif';
} …
```
> fix: default prettier `printWidth: 120` not work as expected

- package.json
- pnpm-lock.yaml
- src/plugins.ts
This PR replaced `eslint-plugin-eslint-comments` with `@eslint-community/eslint-plugin-eslint-comments`.
`@eslint-community/eslint-plugin-eslint-comments` is the successor of `eslint-plugin-eslint-comments` powered by @eslint-community since `eslint-plugin-eslint-comments` is not active in maintained.
None.
None.
> fix: migrate plugin eslint-comments

- src/configs/formatters.ts
- src/utils.ts
- Use explicit scope path for existence checks of ESLint/Prettier plugin deps
- Skip installation of missing packages if current working directory is not in scope of `@antfu/eslint-config`
Fixes #581 
- The existence check for packages that aren't directly used, but just control the config (e.g. `typescript`) is not changed, as for those it makes sense to look in current working directory.
> fix: check packages existence in local scope

- src/configs/javascript.ts
I wanted to enable `no-debugger` when `isEditorEnv`, but apparently there are *two* rules that mess with it
`no-debugger`, `no-with` and `no-labels` are already present, so the `no-restricted-syntax` shouldn't cover them
`vue/no-restricted-syntax` should be kept as it works in `<template>` and `no-debugger`, `no-with` and `no-labels` don't
> fix: remove redundant statements from `no-restricted-syntax`

- src/configs/formatters.ts
- src/vender/prettier-types.ts
Merges plugins list for prettier, allows adding more prettier plugins via `prettierOptions`
Example
```javascript
antfu({
formatters: {
astro: true,
prettierOptions: {
plugins: ['prettier-plugin-tailwindcss'],
},
},
})
```
Closes https://github.com/antfu/eslint-config/issues/613
> feat: merge prettier plugins with options

- package.json
- pnpm-lock.yaml
Update eslint-plugin-vue dependency to solve:
vue/require-valid-default-prop false positive on arrays with props destructure assignment
https://github.com/vuejs/eslint-plugin-vue/issues/2578
Do you need to pay attention to whether the upgrade of eslint-plugin-vue will affect other rules? But it should not be a big problem, it is a patch update
> chore(deps): update eslint-plugin-vue version

- src/cli/run.ts
When using the starter wizard CLI to install `@antfu/eslint-config`, I noticed that the script adds `@antfu/eslint-config` to the package.json, but I forgot to run the command to install dependencies before starting my project.
This oversight can cause confusion for users who might skip this step.
Therefore, I’ve added an install command to the CLI’s outro description to remind users to install dependencies after running the CLI. This change makes it clearer and ensures users are aware they need to install dependencies before starting their work.
**Screenshot:**
---
If you have any feedback or suggestions, please let me know.
> Add install command to cli outro

- src/configs/astro.ts
[Astro uses top level await a lot](https://docs.astro.build/en/guides/data-fetching/#fetch-in-astro):
> Take advantage of top-level await inside of your Astro component script.
> fix: disable `antfu/no-top-level-await` for Astro

- src/configs/react.ts
The react-refresh plugin configuration contains a few rules specific to NextJS and Remix, eliminating a number of unnecessary warnings.
React Router 7 introduces major updates that render `@remix-run/*` imports obsolete. Remix applications now use `@react-router/*` imports instead.
So to allow specific react-refresh rules also working with new React Router 7 apps, we need to detect `@react-router` imports too.
> feat: support React Router 7 in react-refresh rules

- README.md
- package.json
- src/cli/run.ts
Just nitpicking. The dot isn't necessary anymore: https://eslint.org/docs/latest/use/command-line-interface
/
/
> Remove superfluous dot

- src/types.ts
This PR adds support for extending the `RuleOptions` vis ts module augmentation in userland. This can be useful, especially for library authors, when building on top of `@antfu/eslint-config` with custom plugins/configs/rules/etc.
No need for generating types via `eslint-typegen` 👍 
Example in `company/recommended/index.d.ts`:
```ts
declare module '@antfu/eslint-config' {
export interface Rules {
'company/custom-rule': Linter.RuleEntry<[RuleArgs]>
}
}
```
> feat: support rule type augmentations without eslint-typegen

- src/configs/unicorn.ts
- src/types.ts
I just found that it is not able to override `unicorn`'s rules with
```js
antfu({
unicorn: {
overrides: {
}
}
}
```
On the other hand, TS also report type error if users try to override `svelte`'s rules.
And I am trying to fix them
> feat: allow `unicorn` and `svelte` to overrides rules

- src/configs/sort.ts
Hello,
This PR add the keyword `imports` in the `jsonc/sort-keys` applied on `package.json` files.
Keywords already exist for `exports` or `main` but not the `imports` for using [Node subpath imports](https://nodejs.org/docs/latest-v22.x/api/packages.html#subpath-imports).
Usually, I set my "imports" before the "exports" or "main", because from my pov it "affects" the code of a package internally, before the exports are used by another package (or will be parsed by a bundler).
Example:
```json
{
"name": "fake-name",
"type": "module",
"version": "0.0.1",
"private": true,
"imports": {
"#*": "./src/*"
},
"exports": {
".": "./index.ts"
},
...
}
```
Thanks,
> fix(sort): add "imports" key before "exports" for pkg.json

- src/configs/jsonc.ts
- src/configs/vue.ts
`allowMultiplePropertiesPerLine` has been deprecated, use `allowAllPropertiesOnSameLine` instead.
- https://github.com/ota-meshi/eslint-plugin-jsonc/blob/master/lib/rules/object-property-newline.ts
> fix: don't use deprecated option

- src/types.ts
- test/fixtures.test.ts
This PR improves TypeScript compatibility and test reliability:
- **Enhanced type flexibility**: Added `rules` property to `TypedFlatConfigItem` with relaxed typing to support plugin rules that may not be perfectly typed
- **Fixed test timeouts**: Increased timeout on Windows (300s) vs other platforms (30s) to handle slower CI environments
- **Added Next.js support**: Added `nextjs` configuration option with proper JSDoc documentation
The `rules` type enhancement resolves TypeScript errors when using plugin rules with incomplete type definitions. The Windows timeout increase addresses flaky tests in CI environments.
> fix: resolve CI TypeScript and timeout errors

- src/cli/constants-generated.ts
- src/configs/nextjs.ts
- src/types.ts
This PR updates `TypedFlatConfigItem` to provide rules auto-completion and enhances its JSDoc comments.
During testing, I also discovered a few tiny issues, so this PR updates `constants-generated.ts` and adds the missing `name` property to the Next.js rules configuration.
Rules auto-completion stopped working after the last update due to the type changes introduced in PR #738.
---
Thanks for the great config! ;)
> fix: update `TypedFlatConfigItem` to provide rules auto-completion
