- README.md
- pnpm-lock.yaml
- add Usage README
- upgrade partial dependencies for pnpm-lock.yaml
> ref [vitesse](https://github.com/antfu/vitesse)
> docs: add README

- packages/basic/index.js
> chore: replace `no-leading-newline` with `no-multiple-empty-lines`

- packages/basic/index.js
> fix: fixed rules not works

- packages/basic/index.js
index.js --> ignorePatterns array ---> 'packages-lock.json' renamed 'package-lock.json'
> chore(basic): fix typo

- packages/react/index.js
- packages/react/package.json
- pnpm-lock.yaml
Add [Hooks rule](https://reactjs.org/docs/hooks-rules.html) checking to React app.
fixed #116
> feat(react): rules of hooks

- README.md
I previously set Volar as the default formatter for .vue in user's setting, so I won't get formatting right when saving.
Need to overwrite in project settings.
> docs: suggest to disable format on save

- README.md
unable to work without extension .
> docs: add install extension tip

- package.json
- packages/eslint-plugin-antfu/package.json
- pnpm-lock.yaml
> chore: add missing dependency

- packages/basic/index.js
Example:
```ts
const a = 1; const b = 2
```
1. Before this PR being accepted, running `eslint . --fix` will not throw any errors, neither format the declarations to separated line. 
2. After this PR being accepted, running `eslint . --fix` will cause an error.
> feat(basic): add `max-statements-per-line`

- packages/all/package.json
- packages/typescript/package.json
Upgrade "@typescript-eslint/eslint-plugin" and "@typescript-eslint/parser" to support TypeScript 4.9
> feat: support TS 4.9

- packages/typescript/index.js
> feat(ts): add rules that required parserOptions

- packages/typescript/index.js
> fix(ts): fix parerOptions

- packages/basic/index.js
> fix: prefer const when all variables in destructuring should be const

- packages/eslint-plugin-antfu/src/rules/prefer-inline-type-import.ts
There are incorrect description in `prefer-inline-type-import` plugin,  modify `Newline after if` to `Inline type import`
> chore: typo

- packages/vue/index.js
`vue/no-unused-refs` can catch typos in ref names. I don't see any downside in enabling it.
> feat: enable `vue/no-unused-refs`

- packages/eslint-config-basic/index.js
- packages/eslint-config-basic/package.json
- pnpm-lock.yaml
> refactor: remove `eslint-plugin-node`

- packages/eslint-config-basic/index.js
https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/newline-after-import.md
> feat(basic): consider comments for `newline-after-import`

- packages/eslint-config-ts/index.js
Just forget other module solution. Stick to `esm`.
> feat(ts): ban namespace in ts file

- packages/eslint-config-basic/index.js
> fix(basic): allow require imports in js file

- packages/eslint-config-basic/index.js
- packages/eslint-config-ts/index.js
> feat: enable `no-invalid-this`

- package.json
this pr fixes the problem of linting from the root of the project
> chore: run lint script typo

- packages/eslint-config-basic/index.js
> feat: validate `jsonc` file

- packages/eslint-config-vue/package.json
- packages/eslint-config/package.json
- pnpm-lock.yaml
update `eslint-plugin-vue` version to 9.14.0
> feat: update eslint-plugin-vue version

- packages/eslint-config-ts/index.js
https://typescript-eslint.io/rules/consistent-type-assertions/
https://github.com/antfu/eslint-config/issues/187#issuecomment-1563730840
> feat(ts): enable `@typescript-eslint/consistent-type-assertions`

- packages/eslint-config-basic/index.js
> chore(basic): add the missing restricted rules about `window` object

- packages/eslint-config-basic/index.js
> chore: simplified off rules

- packages/eslint-config-basic/standard.js
Sync from remote. Check https://github.com/standard/eslint-config-standard/blob/7d01bbc373bf3bb7374b698323032077ad05f6b1/.eslintrc.json#L130
https://eslint.org/docs/latest/rules/no-mixed-operators
> chore(basic): refesh `standard.js`

- packages/eslint-config-vue/index.js
> feat(vue): enforce order of define macros

- packages/eslint-config-basic/index.js
https://github.com/antfu/eslint-config/pull/194#issuecomment-1577802877
> refactor: use existing rules

- README.md
> docs: make config correct

- packages/eslint-config-vue/index.js
When I'm not using TypeScript, ‘Parsing error: Cannot find module 'typescript'’
> fix: only use eslint in JavaScript

- packages/eslint-config-basic/index.js
Avoid adding undesired @param and @returns lines.
#242
> fix: relax jsdoc rules, fix #242

- src/globs.ts
Include globs for benchmark test files.
https://vitest.dev/config/#benchmark-include
> chore: add `bench` and `benchmark` to GLOB_TESTS

- src/globs.ts
Adds buns package managers lockfile on ignores list
> fix: add lockfile glob for bun

- src/globs.ts
> chore(GLOB_EXCLUDE): add .next

- src/configs/vue.ts
Use the rule recommended by [the official document for Vue](https://vuejs.org/style-guide/rules-strongly-recommended.html#prop-name-casing).
nothing.
nothing.
> fix: Prop names should always use camelCase during declaration.

- .vscode/settings.json
- README.md
Replace
`"source.fixAll": "explicit",`
with
`"source.fixAll.eslint": "explicit",`
Fixes #297
> fix: use "source.fixAll.eslint" to avoid builtin autofixes dropping code

- test/cli.spec.ts
> chore: delete .temp folder after test ends

- src/cli/run.ts
> chore: fix typo

- src/configs/sort.ts
Support packageJson.overrides field as ascending order
> Refer https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides
\-
\-
> feat: support packageJson.overrides field as ascending order

- package.json
- src/configs/sort.ts
Make packageJson.peerDependenciesMeta as ascending order
\-
> feat: make packageJson.peerDependenciesMeta as ascending order

- src/factory.ts
#371 didn't add `getOverrides` in some places, causing #382
#371 
#382
> fix: add overrides missing in #371, close #382

- src/configs/typescript.ts
This splits parser into two FlatConfigItems, one with `project` for type-aware files and one without for type-unaware files
#375
#380 
Tests:
https://github.com/Dimava/antfu-eslint-config/tree/repro/380-works-fine - uses filesTypeAware: ['src/index.ts'], no errors
https://github.com/Dimava/antfu-eslint-config/tree/repro/380-errors-as-expected - doesn't use filesTypeAware, errors with "not in TS project" on many files
> feat: use typescript project only for type-aware files, closes #380

- src/factory.ts
> fix: pick `name` into `fusedConfig`.

- package.json
- pnpm-lock.yaml
- src/configs/formatters.ts
- src/types.ts
- src/utils.ts
An optional prettier plugin for Slidev markdowns
> feat: integrate slidev prettier plugin

- src/cli/run.ts
- test/cli.spec.ts
Files names like eslint.config.* should not be deleted for the reason that they are the main files for eslint configuration
[#417](https://github.com/antfu/eslint-config/issues/417)
> fix: cli-suggest-remove-files

- src/configs/sort.ts
These are the sort fields I usually use, and you can decide what rules are needed of the project. You can modify them directly or bring them up. Happy to contribute :)
- ~`scripts`~
- hooks (`gitHooks`, `husky`, `simple-git-hooks`)
- ~`eslintConfig`~
- ~`stylelint`~
\-
\-
> feat: support more fields of packageJson as ascending order

- src/configs/formatters.ts
Use `GLOB_HTML` file pattern constant for html formatter
> fix: file pattern for htm files

- README.md
The configuration `vue.vueVersion` does exists, but the user has no way to know that.
https://github.com/antfu/eslint-config/issues/443
> docs: explain how to configure the Vue version

- src/configs/react.ts
> feat: add jsx support in react without config.

- README.md
- src/cli/constants.ts
add validation for CSS-related files
> feat(cli): add validation for CSS-related files

- src/cli/run.ts
- src/cli/stages/update-eslint-files.ts
- src/cli/stages/update-package-json.ts
- src/cli/stages/update-vscode-settings.ts
- src/cli/types.ts
Fixed the spelling of the word "prompt"
none
none
> docs: typo

- src/configs/sort.ts
Adds the 'contributors' field to the package.json sort file.
Closes #500
> feat: add 'contributors' to sort (#500)

- README.md
fix #527 
/cc @JoshuaKGoldberg
> docs: rename prefix back

- README.md
> docs: add missing `</details>` tag to README.md

- src/configs/sort.ts
Add `isolatedDeclarations` into the order array in the `sortTsconfig`.
> feat: add `isolatedDeclarations` into the order array

- src/configs/svelte.ts
Delete   'svelte/valid-compile' rule in eslint-plugin-svelte
This rule will be deprecated and it does not work fine for some custom elements
https://github.com/sveltejs/eslint-plugin-svelte/issues/809
> fix: delete `svelte/valid-compile` rule from eslint-plugin-svelte

- .vscode/settings.json
- README.md
- src/cli/constants.ts
> fix: use `fixable: true`

- package.json
- pnpm-lock.yaml
Update eslint-plugin-svelte ASAP
`2.42.0` causes an error 
https://github.com/sveltejs/eslint-plugin-svelte/issues/826
> chore: update eslint-plugin-svelte

- src/factory.ts
- src/utils.ts
Extract and export isInEditorEnv function
#555
> chore: extract isInEditorEnv function

- package.json
- pnpm-lock.yaml
> chore: upgrade install-pkg

- src/configs/react.ts
add Next.js router segment config for `eslint-plugin-react-refresh`
[Ref](https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config)
> fix: add Next.js router segment config

- .vscode/settings.json
- src/cli/constants.ts
enable json5 validate in vscode
> feat: support json5 in vscode

- package.json
Update `prettier-plugin-astro` dependency to avoid peer dependency conflict when latest (`0.14.0`) version is installed.
fixes #636 
This minor version doesn't introduce any breaking changes. Seems that it is safe to bump version of this dependency.
> chore(deps): update prettier-plugin-astro version

- src/cli/constants.ts
add validation for svelte files in vscode
> feat(cli): add validation for svelte files

- src/configs/react.ts
This PR adds support for `@eslint-react/web-api` and synchronizes react config with the recommended plugin rules.
https://eslint-react.xyz/docs/rules/overview#web-api-rules
> feat: add support for @eslint-react/web-api

- README.md
This PR merely fixes the grammar in the recently added "disclaimer" regarding the personal nature of that project.
> docs: Fix grammar in README disclaimer

- src/configs/sort.ts
This adds support for sorting the new flags introduced in ts v5.8
> feat: add ts 5.8 flags

- src/configs/react.ts
This PR sync the recommended rules of react plugins.
> feat: sync the recommended rules of react plugins

- README.md
- package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
- src/configs/imports.ts
- src/configs/stylistic.ts
- src/factory.ts
- src/plugins.ts
- src/types.ts
- src/vender/prettier-types.ts
> feat: bring import plugin back

- src/configs/react.ts
Add allow exports which list in [React Router Document](https://reactrouter.com/start/framework/route-module)
> feat: update allow exports for react-router projects

- src/configs/sort.ts
> feat: support sort jsconfig

- src/configs/sort.ts
Added support for sorting within Bun catalogs
#753
> feat: add sort support of Bun catalogs

- package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
- src/cli/constants-generated.ts
- src/configs/react.ts
adjust some rule names of [React plugin](https://github.com/Rel1cx/eslint-react/releases/tag/v2.0.0).
> feat: update React plugins
